# NumPy Basics <hr style="border:2.5px solid #126782"></hr>

<b>Gyro A. Madrona</b>
<br>Electronics Engineer

In [1]:
# imports and packages
import numpy as np

# 1-D Array

In [2]:
array_a = np.array([1,2,3])
array_a

array([1, 2, 3])

In [4]:
type(array_a)

numpy.ndarray

In [6]:
np.shape(array_a)

(3,)

In [11]:
array_a[2] = 1

In [12]:
array_a

array([1, 2, 1])

In [ ]:
data = [4,5,6]

In [9]:
type(data)

list

In [ ]:
# list to array
array_b = np.array(data)
array_b

array([4, 5, 6])

# 2-D Array

In [13]:
my_array = np.array([
    [1,2,3],
    [4,5,6]
])

In [14]:
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
np.shape(my_array)

(2, 3)

In [16]:
array_a = [1,2,3]
array_b = [4,5,6]

In [ ]:
# lists to array
my_array = np.array([array_a,array_b])
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
my_array = my_array.T

In [22]:
my_array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
# 6 -> 3rd row, 2nd column
# row index = 2, column index = 1
my_array[2][1]

np.int64(6)

# Axis

In [26]:
my_array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
# add rows
my_array.sum(axis=0)

array([ 6, 15])

In [ ]:
# add columns
my_array.sum(axis=1)

array([5, 7, 9])